import {Inter} from "next/font/google";
import "./globals.css";
import {AuthContextProvider} from "@/app/infrastructure/contexts/auth-context";
import {UserContextProvider} from "@/app/infrastructure/contexts/user-context";

const inter = Inter({subsets: ["latin"]});

export const metadata = {
    title: "Essance",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <AuthContextProvider>
            <UserContextProvider>
                {children}
            </UserContextProvider>
        </AuthContextProvider>
        </body>
        </html>
    );
}
