import {Inter} from "next/font/google"; // Importing the Inter font from Google Fonts using Next.js
import "./globals.css"; // Importing global CSS styles
import {AuthContextProvider} from "@/app/infrastructure/contexts/auth-context"; // Importing AuthContextProvider for authentication context
import {UserContextProvider} from "@/app/infrastructure/contexts/user-context"; // Importing UserContextProvider for user-related context

const inter = Inter({subsets: ["latin"]}); // Initializing the Inter font with Latin subset

export const metadata = {
    title: "Essance", // Setting the title metadata for the application
    description: "Generated by create next app", // Setting the description metadata for the application
};

// RootLayout component to provide layout structure and context providers
export default function RootLayout({children}) {
    return (
        <html lang="en"> {/* Setting the language of the document to English */}
        <body className={inter.className}> {/* Applying the Inter font class to the body */}
        <AuthContextProvider> {/* Providing authentication context to the application */}
            <UserContextProvider> {/* Providing user-related context to the application */}
                {children} {/* Rendering child components within the context providers */}
            </UserContextProvider>
        </AuthContextProvider>
        </body>
        </html>
    );
}
